# Generated by Django 6.0.6 on 2026-10-02 14:01

import django.core.validators
import django.db.models.deletion
import safe_eth.eth.django.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0047_chain_zk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayChain',
            fields=[
                ('chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chains.chain')),
                ('relayer_id', models.CharField(help_text="OpenZeppelin Relayer id of this chain's relayer, e.g. <em>base-sepolia</em> (letters, digits, - and _). A relayer of another network sends this chain's transactions to the wrong network.", max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{1,64}\\Z')])),
                ('native_usd_price', models.DecimalField(blank=True, decimal_places=8, help_text='USD per 1 native coin. Empty = the gateway uses its price provider.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('refund_receiver', safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, help_text='Treasury address (checksummed) that receives the Pay from Safe fee refunds.', null=True)),
                ('pay_from_safe_daily_budget_wei', safe_eth.eth.django.models.Uint256Field(blank=True, help_text='Pay from Safe: gas the relayer may reserve per UTC day, in wei (1 ETH = 1000000000000000000). Empty = no budget.', null=True, validators=[django.core.validators.MinValueValidator(1)])),  # type: ignore[no-untyped-call]
                ('sponsoring_daily_budget_wei', safe_eth.eth.django.models.Uint256Field(blank=True, help_text='Sponsoring: gas the relayer may reserve per UTC day, in wei (1 ETH = 1000000000000000000). Set all four sponsoring fields or none.', null=True, validators=[django.core.validators.MinValueValidator(1)])),  # type: ignore[no-untyped-call]
                ('sponsoring_per_safe_per_day', models.PositiveIntegerField(blank=True, help_text='Sponsoring: relays per Safe account per UTC day.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sponsoring_per_owner_creations_per_day', models.PositiveIntegerField(blank=True, help_text='Sponsoring: account creations per owner per UTC day. 0 = sponsored creation off.', null=True)),
                ('sponsoring_max_gas_limit', models.PositiveIntegerField(blank=True, help_text='Sponsoring: maximum gas limit of one relayed transaction.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='RelayFeeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', safe_eth.eth.django.models.EthereumAddressBinaryField(help_text="Token contract address, checksummed. 0x0000000000000000000000000000000000000000 = the chain's native coin.")),
                ('symbol', models.CharField(max_length=32)),
                ('decimals', models.PositiveSmallIntegerField()),
                ('usd_price', models.DecimalField(blank=True, decimal_places=8, help_text='USD per 1 token. Empty = the gateway uses its price provider. Must be empty for the native coin.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('relay_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='relay.relaychain')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('relay_chain', 'address'), name='unique_relay_fee_token')],
            },
        ),
    ]
