# Generated by Django 6.0.6 on 2026-10-05 14:43

import safe_eth.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaychain',
            name='refund_receiver',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, help_text='Treasury address (checksummed) that receives the Pay from Safe fee refunds. Must be an EOA (no contract code) if the native coin is a fee token: the Safe refunds the native coin with a 2300-gas send, which a contract such as a Safe cannot receive, so the transaction reverts with GS011. Token refunds work with any receiver.', null=True),
        ),
        migrations.AlterField(
            model_name='relayfeetoken',
            name='address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(help_text="Token contract address, checksummed. 0x0000000000000000000000000000000000000000 = the chain's native coin; list it only when the refund receiver is an EOA."),
        ),
    ]
